<?php
/** @var \Magento\Backend\Block\Template $block */
$blockId = $block->getRequest()->getParam('page_id');
if (!$blockId) return;

$formKey = $block->getFormKey();
?>
<form action="<?= $block->getUrl('cms/page/export') ?>" method="post" class="export-button">
    <input type="hidden" name="form_key" value="<?= $formKey ?>">
    <input type="hidden" name="page_id" value="<?= $blockId ?>">
    <button type="submit" class="action-default primary">
        <span><?= __('Export Page CSV') ?></span>
    </button>
</form>
